#server:
#    port: 8085
#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        password: Wbjee.cgi@2018
#        url: jdbc:mysql://localhost:3306/Keepnote
#        username: root
#    jpa:
#        generate-ddl: false
#        hibernate:
#            ddl-auto: create
#        openInView: false
#        show_sql: true
server:
  port: 8098  #default port where the service will be started

#eureka:         #tells about the Eureka server details and its refresh time
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
cloud:
    config:
        uri:  http://localhost:8888

spring:
  application:
    name: movie-service   #current service name to be used by the eureka server

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    com.stackroute.movieservice: DEBUG